import {
	PUBLIC_SUPABASE_ANON_KEY,
	PUBLIC_SUPABASE_LOCAL_ANON_KEY,
	PUBLIC_SUPABASE_LOCAL_URL,
	PUBLIC_SUPABASE_URL
} from "$env/static/public"
import { dev } from "$app/environment"

export const SUPABASE_URL = dev ? PUBLIC_SUPABASE_LOCAL_URL : PUBLIC_SUPABASE_URL
export const SUPABASE_ANON_KEY = dev ? PUBLIC_SUPABASE_LOCAL_ANON_KEY : PUBLIC_SUPABASE_ANON_KEY
